version: 1.0.{build}

install:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: Calc.sln
  verbosity: detailed

environment:
  COVERALLS_REPO_TOKEN:  
    secure: b7577bRaOs3mFdYlr8nRoHhJHDXYzNPZT6EizY0h2cG+FgLvFMnjYWJx/9lhQS3U

test_script:
  - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  Calc.Tests\bin\debug\Calc.Tests.dll" -output:"coverage.xml"
  - codecov -f "coverage.xml"
