version: 1.0.{build}

image: Visual Studio 2015

install:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: Calc.sln
  verbosity: detailed

environment:
  COVERALLS_REPO_TOKEN:  
    secure: b7577bRaOs3mFdYlr8nRoHhJHDXYzNPZT6EizY0h2cG+FgLvFMnjYWJx/9lhQS3U

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Calc.Tests\bin\Debug\Calc.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[Calc.Tests*]*" -output:".\coverage.xml"
  - codecov -f "coverage.xml
